기초적인 viewmodel 반영(학습자용) - 프론트 엔드 작업 완료
SUVID-18/check_attendance_student pull request #48
Opened 2023-05-28 12:58 UTC by 000hgf

2023-05-28 13:37 UTC, sun30812 requested changes
코멘트 확인 바랍니다.

2023-05-28 13:37 UTC, sun30812 commented on lib/view/register_device.dart
> +///min
?

2023-05-28 13:37 UTC, sun30812 commented on lib/view/register_device.dart
>    String name = '';
불필요한 변수 의심

2023-05-28 13:37 UTC, sun30812 commented on lib/view/settings_page.dart
> +                                    ///Text('이름: ${viewModel.userName}'),
코드 누락?

2023-05-29 00:04 UTC, sun30812 commented on lib/view/login.dart
> +                      if (viewModel.emailController.text.isNotEmpty)
별도 핸들링 로직 구현 안하셔도 됩니다.

2023-05-29 00:25 UTC, sun30812 requested changes
추가로 main_page.dart에 NetworkImage있는데 ImageAsset으로 사용할 수 있게 조치 하시면 될 듯 합니다.

2023-05-30 00:00 UTC, sun30812 approved these changes
아래 두 기능에 대해 동작이 확인되므로 변경 내용을 승인함.

* 로그인 관련 기능(로그인, 로그아웃) 및 학생 정보 표시 구현 확인
* 출석체크 기능 구현 확인

2023-05-30 08:40 UTC, Planybirth approved these changes
뷰모델을 불러와서 데이터베이스에 접근한 정보를 띄움을 확인했습니다!
처리된 이슈번호까지만 딱 써주면 완벽할 것 같아요

2023-06-05 02:31 UTC, dongminii commented
넵

2023-06-05 02:32 UTC, dongminii approved these changes

2023-06-05 02:32 UTC, merged